# Copyright (c) HephaestusProject
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# This your_mode.yml was made by soeque1 at 24/07/20.
# writing configuration of your dataset.

output_size: 256
vocab_size: 30522
embed_size: 128
utter_hidden_size: 256
utter_n_layer: 1
batch_size: 128
dropout: 0.1
out_size: 512
max_seq: 50
max_turns: 10
