pl:
    gpus: [0]
    num_nodes: 1
    accelerator: ddp
    amp_level: O2
    amp_backend: native
    max_epochs: 300
data:
    batch_size: 128
    num_workers: 4
    shuffle: False
    fast_dev_run: False
lr: 6.25e-5
gradient_accumulation_steps: 1
warmup_steps: 500
weight_decay: 0.01