pl:
    num_nodes: 1
    distributed_backend: ddp_cpu
    precision: 32
    max_epochs: 1
data:
    batch_size: 2
    num_workers: 1
    shuffle: False
lr: 6.25e-5
gradient_accumulation_steps: 1
warmup_steps: 500
weight_decay: 0.01